#ifndef BSDF_LOBES_H
#define BSDF_LOBES_H

enum BSDF_LOBE : unsigned int {
	BSDF_LOBE_DIFFUSE_REFLECTION = 1 << 0,
	BSDF_LOBE_DIFFUSE_TRANSMISSION = 1 << 1,
	BSDF_LOBE_GLOSSY_REFLECTION = 1 << 2,
	BSDF_LOBE_GLOSSY_TRANSMISSION = 1 << 3,
	BSDF_LOBE_DELTA_REFLECTION = 1 << 4,
	BSDF_LOBE_DELTA_TRANSMISSION = 1 << 5,
	BSDF_LOBE_REFLECTION = BSDF_LOBE_DIFFUSE_REFLECTION | BSDF_LOBE_GLOSSY_REFLECTION | BSDF_LOBE_DELTA_REFLECTION,
	BSDF_LOBE_TRANSMISSION = BSDF_LOBE_DIFFUSE_TRANSMISSION | BSDF_LOBE_GLOSSY_TRANSMISSION | BSDF_LOBE_DELTA_TRANSMISSION,
	BSDF_LOBE_DELTA = BSDF_LOBE_DELTA_REFLECTION | BSDF_LOBE_DELTA_TRANSMISSION,
	BSDF_LOBE_NON_DELTA = BSDF_LOBE_DIFFUSE_REFLECTION | BSDF_LOBE_DIFFUSE_TRANSMISSION | BSDF_LOBE_GLOSSY_REFLECTION | BSDF_LOBE_GLOSSY_TRANSMISSION,
	BSDF_LOBE_ALL = BSDF_LOBE_DELTA | BSDF_LOBE_NON_DELTA
};

#endif